# Generated by Django 4.0.6 on 2022-08-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flightroute_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightroute',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flight_routes', to='flights.location'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flight_routes', to='flights.location'),
        ),
    ]
