# Generated by Django 4.0.6 on 2022-08-08 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_airpalne_flightroute_airplane'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='korean_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
